CREATE DATABASE M_MModa
USE M_MModa

CREATE TABLE Marca (
	IdMarca INT PRIMARY KEY IDENTITY
	, Marca VARCHAR(200) UNIQUE NOT NULL
);
CREATE TABLE Modelo (
	IdModelo INT PRIMARY KEY IDENTITY
	, Modelo VARCHAR(200) UNIQUE NOT NULL
	, IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca)
);
CREATE TABLE Cor (
	IdCor INT PRIMARY KEY IDENTITY
	, Cor VARCHAR(200) UNIQUE NOT NULL
);
CREATE TABLE Tamanho (
	IdTamanho INT PRIMARY KEY IDENTITY
	, Tamanho VARCHAR(200) UNIQUE NOT NULL
);
CREATE TABLE Roupa (
	IdRoupa INT PRIMARY KEY IDENTITY
	, IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo)
	, IdCor INT FOREIGN KEY REFERENCES Cor(IdCor)
	, IdTamanho INT FOREIGN KEY REFERENCES Tamanho(IdTamanho)
);