CREATE DATABASE M_SStop;
USE M_SStop;

CREATE TABLE EstilosMusicais(
	IdEstilosMusicais INT PRIMARY KEY IDENTITY
	, Nome VARCHAR(200) UNIQUE NOT NULL
);
CREATE TABLE Artistas(
	IdArtista INT PRIMARY KEY IDENTITY
	, IdEstilosMusicais INT FOREIGN KEY REFERENCES EstilosMusicais(IdEstilosMusicais)
);

ALTER TABLE Artistas
ADD Nome VARCHAR(200) UNIQUE PRIMARY KEY IDENTITY;